#!/usr/bin/env bash
set -euo pipefail

footer='Changelog generated by [cocogitto](https://github.com/cocogitto/cocogitto).'

die() {
	echo "changelog: $1" >&2
	exit 1
}

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
changelog="$root/CHANGELOG.md"

[ -f "$changelog" ] || die "no changelog at $changelog"

mode='write'
case "${1-}" in
--check)
	mode='check'
	shift
	;;
--amend)
	mode='amend'
	shift
	;;
esac

[ $# -eq 0 ] || die "usage: $0 [--check|--amend]"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

first_of_each() {
	awk -v footer="$footer" '
		$0 == footer { next }
		/^## \[/ {
			if ($0 in seen) { exit }
			seen[$0] = 1
		}
		{ print }
	' "$changelog"
}

trim() {
	tac | awk '
		!started && (NF == 0 || $0 == "- - -") { next }
		{ started = 1; print }
	' | tac
}

first_of_each | trim >"$work/body"
[ -s "$work/body" ] || die 'the changelog holds no release'

{
	cat "$work/body"
	printf '\n- - -\n\n%s' "$footer"
} >"$work/CHANGELOG.md"

kept=$(grep -c '^## \[' "$work/CHANGELOG.md" || true)
had=$(grep -c '^## \[' "$changelog" || true)

if cmp -s "$work/CHANGELOG.md" "$changelog"; then
	echo "changelog: $kept release(s), none repeated"
	exit 0
fi

problem='the changelog is not shaped the way this script writes it'
[ "$had" -le "$kept" ] || problem="the changelog repeats $((had - kept)) release(s)"

[ "$mode" != 'check' ] || die "$problem; run $0"

cp "$work/CHANGELOG.md" "$changelog"
echo "changelog: kept $kept release(s), dropped $((had - kept))"

[ "$mode" = 'amend' ] || exit 0

mapfile -t tags < <(git -C "$root" tag --points-at HEAD)
[ "${#tags[@]}" -le 1 ] || die "HEAD carries ${#tags[@]} tags; none was moved"

git -C "$root" add CHANGELOG.md
git -C "$root" commit --amend --no-edit --no-verify >/dev/null
echo "changelog: amended $(git -C "$root" rev-parse --short HEAD)"

[ "${#tags[@]}" -eq 1 ] || exit 0

git -C "$root" tag -f "${tags[0]}" HEAD >/dev/null
echo "changelog: moved ${tags[0]} onto the amended commit"
