mod attributes;
mod auto;
mod block;
mod clone;
mod commit;
mod constants;
mod empty;
#[cfg(test)]
pub mod fixture;
mod ignore;
mod info;
mod init;
mod lfs;
mod locks;
mod push;
mod rules;
mod run;
mod scratch;
mod stage;

pub use attributes::{path as attributes_path, sync as sync_attributes};
pub use auto::auto;
pub use clone::{Cloned, clone, clone_plain};
pub use commit::{commit, committed, message, staged};
pub use ignore::{Excludes, Kind};
pub use info::refresh as refresh_info;
pub use init::init;
pub use lfs::{available as lfs_available, install as install_lfs};
pub use locks::guard as guard_locks;
pub use push::push;
pub use run::present;
pub use scratch::{record, scratch};
pub use stage::{stage, stage_all, unstage};
