stages:
  - test
  - release
  - mirror
  - binaries
  - publish

default:
  tags:
    - k8s

include:
  - local: .gitlab/workflows/test.yml
  - local: .gitlab/workflows/release.yml
  - local: .gitlab/workflows/mirror.yml
  - local: .gitlab/workflows/binaries.yml
  - local: .gitlab/workflows/aur.yml
