mod add_cmd;
mod apply_cmd;
mod bootstrap_cmd;
mod cd_cmd;
mod class_cmd;
mod clone_cmd;
mod completions_cmd;
mod config_cmd;
mod diff_cmd;
mod doc_cmd;
mod edit_cmd;
mod exec_cmd;
mod git_cmd;
mod init_cmd;
mod man_cmd;
mod push_cmd;
mod rekey_cmd;
mod restore_cmd;
mod rm_cmd;
mod setup_cmd;
mod status_cmd;
mod sync_cmd;
mod tmpl_cmd;

pub use add_cmd::{AddArgs, add_cmd};
pub use apply_cmd::{ApplyArgs, apply_cmd};
pub use bootstrap_cmd::bootstrap_cmd;
pub use cd_cmd::cd_cmd;
pub use class_cmd::{ClassArgs, class_cmd};
pub use clone_cmd::{CloneArgs, clone_cmd};
pub use completions_cmd::{CompletionsArgs, completions_cmd};
pub use config_cmd::{ConfigArgs, config_cmd};
pub use diff_cmd::{DiffArgs, diff_cmd};
#[cfg(test)]
pub use doc_cmd::documented;
pub use doc_cmd::{DocArgs, doc_cmd};
pub use edit_cmd::{EditArgs, edit_cmd};
pub use exec_cmd::{ExecArgs, exec_cmd};
pub use git_cmd::{GitArgs, git_cmd};
pub use init_cmd::{InitArgs, init_cmd};
pub use man_cmd::man_cmd;
pub use push_cmd::{PushArgs, push_cmd};
pub use rekey_cmd::{RekeyArgs, rekey_cmd};
pub use restore_cmd::{RestoreArgs, restore_cmd};
pub use rm_cmd::{RmArgs, rm_cmd};
pub use setup_cmd::{SetupArgs, setup_cmd};
pub use status_cmd::{StatusArgs, status_cmd};
pub use sync_cmd::{SyncArgs, sync_cmd};
#[cfg(test)]
pub use tmpl_cmd::TmplAction;
pub use tmpl_cmd::{TmplArgs, tmpl_cmd};
